# Minimal Calendar Notifier Configuration
# This is the bare minimum configuration to get started

nats:
  url: "nats://localhost:4222"
  subject: "calendar.notifications"

calendars:
  - name: "my-calendar"
    type: "caldav"
    # Google Calendar CalDAV URL (replace with your email)
    url: "https://calendar.google.com/calendar/dav/your-email@gmail.com/events"
    username: "your-email@gmail.com"
    password: "your-app-password"  # Generate app password in Google Account settings
    poll_interval: "5m"

defaults:
  notification_intervals: [15, 5]
  default_severity: "normal"

logging:
  level: "info"
  format: "json"