# Calendar Notifier Configuration Example
# Copy this file to config.yaml and customize for your environment

# NATS message broker configuration
nats:
  # NATS server URL - can be a single server or comma-separated list for clustering
  url: "nats://localhost:4222"
  # Subject to publish calendar notifications to
  # This should match what your calendar-siren consumer is listening on
  subject: "calendar.notifications"

# Calendar provider configurations
# You can configure multiple calendars from different providers
calendars:
  # CalDAV configuration (works with Apple, Outlook, Nextcloud, etc.)
  - name: "my-calendar"
    type: "caldav"
    # CalDAV server URL - see examples below for different providers
    url: "https://caldav.example.com/user/calendar/"
    username: "your-username"
    password: "your-app-password"  # Use app password, not your main password!
    poll_interval: "5m"

  # Example: Apple iCloud Calendar
  - name: "icloud-calendar"
    type: "caldav"
    url: "https://caldav.icloud.com/[your-calendar-id]/calendars/[specific-calendar]/"
    username: "your-apple-id@icloud.com"
    password: "your-app-specific-password"
    poll_interval: "5m"

  # Example: Outlook/Office365 Calendar
  - name: "outlook-calendar"
    type: "caldav"
    url: "https://outlook.office365.com/EWS/Exchange.asmx"
    username: "your-email@outlook.com"
    password: "your-password"
    poll_interval: "5m"

  # Example: iCal URL (public calendars)
  - name: "public-ical"
    type: "ical"
    url: "https://example.com/calendar.ics"
    poll_interval: "10m"

# Default notification settings
defaults:
  # Default notification intervals in minutes before event start
  # These are used when events don't have their own alarm/reminder settings
  notification_intervals: [15, 5]  # 15 minutes and 5 minutes before

  # Default severity level for notifications
  # Options: "low", "normal", "high", "critical"
  default_severity: "normal"

# Logging configuration
logging:
  # Log level: "debug", "info", "warn", "error"
  level: "info"
  # Log format: "json" (recommended for production) or "text" (human readable)
  format: "json"