# Minimal Calendar Notifier Configuration
# This is the bare minimum configuration to get started

nats:
  url: "nats://localhost:4222"
  subject: "calendar.notifications"

calendars:
  - name: "my-calendar"
    type: "caldav"
    # CalDAV server URL (replace with your server details)
    url: "https://caldav.example.com/user/calendar/"
    username: "your-username"
    password: "your-app-password"  # Use app-specific password
    poll_interval: "5m"

defaults:
  notification_intervals: [15, 5]
  default_severity: "normal"

logging:
  level: "info"
  format: "json"