# Basic configuration for calendar-notifier
# This example shows a simple setup with a single iCal calendar

# NATS configuration for publishing notifications
nats:
  url: "nats://localhost:4222"
  subject: "calendar.notifications"

# Calendar sources to monitor
calendars:
  - name: "personal-calendar"
    type: "ical"
    url: "https://calendar.example.com/calendar.ics"
    poll_interval: "5m"
    calendar_ids: []  # Use all calendars from the source

# Default notification settings
defaults:
  # Default notification intervals (in minutes before event)
  # Applied to events that don't have their own alarms
  notification_intervals: [15, 30]
  # Default severity for notifications
  default_severity: "normal"

# Logging configuration
logging:
  level: "info"       # debug, info, warn, error
  format: "json"      # json, text